### ISSUE TITLE
Start Menu

### ISSUE THREAD

**Issue by Jalict** [KasperHdL/Summer-Game-Jam#21]
- [x] Start game zoomed in on the island. Where you can see each 4 slot (Players, 2x boats 2x surfs)
- [x]  Players can choose which slot they want to occupy using Y X A B
- [x] Start game when players are ready - Camera zooms out so whole map can be seen

**Comment by Jalict** [comment]
So if Player 1 presses Y. Then the Y slot is occupied and no one else can take that.
Then player 2 can press X, A or B. They choose B.
Now Player 3 and 4 can't choose Y or B. So X and A is empty. Etc.

**Comment by Jalict** [comment]
Timer starts when all slots have been occupied or something like that.
But that doesn't allow AI or empty slots though.

**Comment by KasperHdL** [comment]
we could just say every slot not occupied is AI
